spring.application.name=restpro
server.port=8080



spring.datasource.url=jdbc:postgresql://localhost:5432/music_library
spring.datasource.username=postgres
spring.datasource.password=z050311
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true